fix(app)!: move the configuration of Jetpack Compose to separate plugin
The app will crash after start with "NoSuchMethodError: No static method setContent" exception. This occured because configuration of compose should be done before "afterEvaluate"

# Ref: https://issuetracker.google.com/issues/195273509